ask/urls.py
from django.conf.urls import patterns, url
from ask import views

urlpatterns = patterns('',
    url(r'^helloworld/', views.helloworld, name='helloworld'),
    url(r'^$', views.index,),
    url(r'^question/(\d+)', views.question),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': 'request.path'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^answer/(\d+)', views.answer),
    url(r'^search/$', views.search,),
)

ask_Linnik/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_Linnik.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('ask.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ask/models.py
from django.db import models
from django.contrib.auth.models import User
from djangosphinx.models import SphinxSearch
from django.core.files.storage import FileSystemStorage

# Create your models here
class Profile(models.Model):
    user = models.OneToOneField(User)
    rating = models.IntegerField(default=0)
    avatar = models.CharField(max_length=60)
    
User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])
    
class Tags(models.Model):
    tag = models.CharField(max_length=20)   
   
class Question(models.Model):
    author = models.ForeignKey(Profile)
    title = models.CharField(max_length=60)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    tag_list = models.ManyToManyField(Tags)
    
    
    search = SphinxSearch(
        index = 'ask_question_idx', 
        weights = { 'title':100, 'text':20 },
    )

class Answer(models.Model):
    author = models.ForeignKey(Profile)
    question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_right = models.BooleanField(default=False)
    
class Image(models.Model):
    docfile = models.ImageField("Image", upload_to='image/%Y/%m/%d')

templates/inc/answer.html
<div class="question">
    <div class="row">
        <div class="span2">
            <div class="Nick">
                <h6>Author: {{ a.author.user }} </h6>
                {% if a.is_right == 1%}
                    <div>
                        <FONT COLOR=#A31092>Right answer!</FONT>
                    </div>
                {% endif %}
                
                {% if user.is_authenticated %}
                    {% if user.id == q.author_id %} 
                        
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="span5">
            <p> {{a.text}} </p>
        </div>
    </div>
</div>

templates/inc/best_tags.html
<ul>
    {% for t in tags %}
    <li>{{t.tag}} = {{t.count_quest}}</li>
    {% endfor %}
</ul>

templates/inc/best_users.html
<ul>
    {% for q in questions %}
    <li>{{q.author}} = {{q.rating}}</li>
    {% endfor %}
</ul>

templates/inc/logged.html
<div class="user-block" style="padding: 5px 0;">
    <img src="http://lorempixel.com/40/40/" style="float:left;">
    <span>
        <div class="Nick" >
            <h6 style=" margin: 0 0;">{{ user }} </h6>
        </div>
        <div style="text-align: center;">
            <a href="{% url 'profile' %}">Settings </a> 
            <a href="{% url 'logout' %}?next={{ request.get_full_path }}">Log out</a>
        </div>
    </span>
</div>

templates/inc/notlogged.html
<div class="user-block">
    <span>
        <a class="btn" href="{% url 'login' %}?next={{ request.path }}">Login</a> 
        <a class="btn" href="/signup/?next={{ request.get_full_path }}">Sign up</a>
    </span>
</div>

templates/inc/paginator.html
<div class="Paginator">
    {% if question_list.has_previous %}
        <a href="?page={{ question_list.previous_page_number }}" class="btn btn-primary">Prev</a>
    {% endif %}

    <span class="label label-info">
        Page {{ question_list.number }} of {{ question_list.paginator.num_pages }}
    </span>

    {% if question_list.has_next %}
        <a href="?page={{ question_list.next_page_number }}" class="btn btn-primary">Next</a>
    {% endif %}
</div>

templates/inc/question.html
<div class="question">
    <div class="row">
        <div class="span2">
            <img src="http://lorempixel.com/120/120/" class="img-polaroid">
            <div>
                <a href="#" class="img">
                    <img src="../img/plus.png" alt="..." style="width:40px;height:40px; class="img-circle"">
                </a>
                <span class="badge badge-success">{{q.rating}}</span></a>
                <a href="#" class="img">
                <img src="../img/minus.jpg" alt="..." style="width:40px;height:40px; class="img-circle"">
                </a>
                <div class="Nick">
                    {% if user.is_authenticated %}
                        {% if user.id == q.author.id %}
                            <h6>Author: You </h6>
                        {% else %}
                            <h6>Author: {{ q.author.user }} </h6>
                        {% endif %}
                    {% else %}
                        <h6>Author: {{ q.author.user }} </h6>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="span5">
            <h4><a href="/question/{{q.id}}"> {{q.title}} </a></h4>
            <p> {{q.text}} </p>
            <div>
                <a href="/question/{{q.id}}" class="btn btn-primary">Check answers ({{q.answer_set.count}} already)</a>
                <h5>Tags: </h5>
                <ul class="list">
                    {%for t in q.tag_list.all%}
                    <li>{{t.tag}}</li>
                    {%endfor%}
                </ul>
            </div>
        </div>
    </div>
</div>